#!/bin/bash

set -e
set -o pipefail

DOCUMENT_GENERATOR_DIR="../scanarium-document-generator"

error() {
    echo "ERROR" "$@" >&2
    exit 1
}

check_version_numbers() {
    "$DOCUMENT_GENERATOR_DIR/tools/pre-commit-hook-increasing-version-number"
}

assert_at_most_one_sentence_per_line() {
    # This is backwards and hugely ineffective. But it takes less than
    # 0.01 seconds, so I won't set this straight for now.
    if grep -vnr '^\({=macro(\|[0-9]\+\.\)' source | grep '[^.B][!?.] '
    then
        error "Found lines (see above) with more than one sentence per line"
    fi
}

run() {
    check_version_numbers
    assert_at_most_one_sentence_per_line
}
run
